[project]
name = "blog-autobuild"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "inflector>=3.1.1",
    "pyyaml>=6.0.3",
]
